apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: nirop-sing
  name: nirop-sing
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nirop-sing
  template:
    metadata:
      labels:
        service: nirop-sing
    spec:
      containers:
      - image: girishnaik/nirop-sing
        name: nirop-sing
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080                      
      restartPolicy: Always