apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: nirop-keel
  name: nirop-keel
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nirop-keel
  template:
    metadata:
      labels:
        service: nirop-keel
    spec:
      containers:
      - image: girishnaik/nirop-keel
        name: nirop-keel
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                  
        env:
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: FRONTEND_URL
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_BUCKET
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_REGION
        - name: CONVERSATION_TABLE_NAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: CONVERSATION_TABLE_NAME
        - name: CONVERSATION_TABLE_UDATE_IDX
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: CONVERSATION_TABLE_UDATE_IDX
        - name: CONVERSATION_TABLE_CID_IDX
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: CONVERSATION_TABLE_CID_IDX
        - name: JWKS_URL
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: JWKS_URL
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: PORT      
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true        
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret       